apiVersion: v1
kind: Pod
metadata:
        name: sample-jenkins
spec:
   containers:
           - name: jenkins
             image: jenkins
             ports:
             - containerPort: 8080        

