apiVersion: v1
kind: Pod
metadata:
        name: sample-jenkins
specs:
   containers:
           - name: Jenkins
             image: jenkins
             ports:
             - containerPort: 8080        

