apiVersion: v1
kind: ReplicationController
metadata:
  name: replication 
spec: 
  replicas: 5
  selector:
    app: jenkins
  template:
    metadata: 
      labels:
        app: jenkins
    spec:
    #hostNetwork: true
      containers:
        - name: jenkins
          image: jenkins
          ports: 
            - containerPort: 8080


