apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins 
  namespace: default
spec: 
  replicas: 5
  selector:
    app: jenkins
  template:
    metadata: 
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins
          ports: 
            - containerPort: 8080


