apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec: 
  selector:
    app: jenkins
#  type: NodePort 
    type: LoadBalancer 
  ports:
  - name: test 
    port: 8080
#    nodePort: 30001
    protocol: TCP 
